version: "3"
volumes:
  node_modules:
services:
  shopee-test:
    build: .
    environment:
      - REGION=local
      - ROLE=""
      - IS_DEV=true
    command: bash -c "npm run test"
    ports:
      - "3000:3000" # for sns offline event
    volumes:
      - .:/app
      - node_modules:/app/node_modules